services:
  php-apache:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php_apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  database:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quental
      MYSQL_USER: juanra
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
